apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulytix-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neb-backend
  template:
    metadata:
      labels:
        app: neb-backend
    spec:
      containers:
        - name: neb-backend
          image: 935743309939.dkr.ecr.ap-south-1.amazonaws.com/nebulytixbackend:latest 
          ports:
            - containerPort: 5054
       