apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulytix-fortend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neb-fortend
  template:
    metadata:
      labels:
        app: neb-fortend
    spec:
      containers:
        - name: neb-fortend
          image: 935743309939.dkr.ecr.ap-south-1.amazonaws.com/nebulytixfortend:latest
          ports:
            - containerPort: 5054
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://<my-RDS-ENDPOINT>:3306/nebulytix_db
            - name: SPRING_DATASOURCE_USERNAME
              value: neb_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: Neb@123  
       